### PR TITLE
minor updates to atlas metagenome lesson

### PR DESCRIPTION
**Pull request by ctb**
for @taylorreiter to review and merge at end of lesson.

### CODE REVIEW

**Comment by ctb** [comment]
comment from within class - maybe change the environment name away from `atlas`? it's confusing people

**Comment by ctb** [comment]
I'm going to tag @taylorreiter in on this again anyway

**Comment by ctb** [comment]
even tho @AstrobioMike merged it :)

**Comment by AstrobioMike** [comment]
too efficient for my own good (or too something)

**Comment by ctb** [comment]
:) quick to push button!

On Tue, Jul 30, 2019 at 07:39:03AM -0700, Mike Lee wrote:
> too efficient for my own good (or too something)
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mblstamps/stamps2019/pull/6#issuecomment-516448686
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Pull request merged**
